# Form implementation generated from reading ui file '.\templates\dlgGestionprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgTipoProp(object):
    def setupUi(self, dlgTipoProp):
        dlgTipoProp.setObjectName("dlgTipoProp")
        dlgTipoProp.resize(362, 279)
        self.widget = QtWidgets.QWidget(parent=dlgTipoProp)
        self.widget.setGeometry(QtCore.QRect(0, 0, 361, 271))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setObjectName("frame")
        self.txt = QtWidgets.QLineEdit(parent=self.frame)
        self.txt.setGeometry(QtCore.QRect(90, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt.sizePolicy().hasHeightForWidth())
        self.txt.setSizePolicy(sizePolicy)
        self.txt.setMinimumSize(QtCore.QSize(150, 20))
        self.txt.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.txt.setFont(font)
        self.txt.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.txt.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txt.setObjectName("txt")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(40, 30, 270, 20))
        self.label.setMinimumSize(QtCore.QSize(270, 20))
        self.label.setMaximumSize(QtCore.QSize(270, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltaTipoProp = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltaTipoProp.setObjectName("btnAltaTipoProp")
        self.horizontalLayout.addWidget(self.btnAltaTipoProp)
        self.btnBajaTipoProp = QtWidgets.QPushButton(parent=self.widget)
        self.btnBajaTipoProp.setObjectName("btnBajaTipoProp")
        self.horizontalLayout.addWidget(self.btnBajaTipoProp)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgTipoProp)
        QtCore.QMetaObject.connectSlotsByName(dlgTipoProp)

    def retranslateUi(self, dlgTipoProp):
        _translate = QtCore.QCoreApplication.translate
        dlgTipoProp.setWindowTitle(_translate("dlgTipoProp", "Gestión - Tipo Propiedades"))
        self.label.setText(_translate("dlgTipoProp", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltaTipoProp.setText(_translate("dlgTipoProp", "Alta"))
        self.btnBajaTipoProp.setText(_translate("dlgTipoProp", "Baja"))
