# Form implementation generated from reading ui file '.\templates\dlgGestipoprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgGestipoprop(object):
    def setupUi(self, dlgGestipoprop):
        dlgGestipoprop.setObjectName("dlgGestipoprop")
        dlgGestipoprop.resize(362, 278)
        self.frame = QtWidgets.QFrame(parent=dlgGestipoprop)
        self.frame.setGeometry(QtCore.QRect(0, 0, 359, 181))
        self.frame.setObjectName("frame")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestipoprop.setGeometry(QtCore.QRect(100, 150, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGestipoprop.sizePolicy().hasHeightForWidth())
        self.txtGestipoprop.setSizePolicy(sizePolicy)
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.txtGestipoprop.setFont(font)
        self.txtGestipoprop.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.txtGestipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.lblGestipoprop = QtWidgets.QLabel(parent=self.frame)
        self.lblGestipoprop.setGeometry(QtCore.QRect(50, 130, 270, 20))
        self.lblGestipoprop.setMinimumSize(QtCore.QSize(270, 20))
        self.lblGestipoprop.setMaximumSize(QtCore.QSize(270, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGestipoprop.setFont(font)
        self.lblGestipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGestipoprop.setObjectName("lblGestipoprop")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 131, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\templates\\../img/gestipopro.ico"))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=dlgGestipoprop)
        self.widget.setGeometry(QtCore.QRect(100, 210, 158, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")
        self.horizontalLayout.addWidget(self.btnAltatipoprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)

        self.retranslateUi(dlgGestipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlgGestipoprop)

    def retranslateUi(self, dlgGestipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlgGestipoprop.setWindowTitle(_translate("dlgGestipoprop", "Gestión - Tipo Propiedades"))
        self.lblGestipoprop.setText(_translate("dlgGestipoprop", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltatipoprop.setText(_translate("dlgGestipoprop", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgGestipoprop", "Baja"))
